describe('Testing the UI with reponse from API', () => {
  it('Opens the application and waits for API response', () => {
    cy.visit('http://localhost:3000')
    cy.intercept('GET', '/prod/v0/rest/lightning').as('getLightning')
    cy.get('[aria-label=loading-text]').should('contain.text', 'Loading, please wait...')
    cy.wait('@getLightning')
  })
  it('Tests each view in the Console', () => {
    cy.wait(1000)
    cy.get('[id=map-component]').screenshot()
    cy.get('[aria-label=console-drawer-icon-Dashboard]').click()
    cy.wait(1000)
    cy.get('[id=dashboard]').screenshot()
    cy.get('[aria-label=console-drawer-icon-Table]').click()
    cy.wait(1000)
    cy.get('[id=table-component]').screenshot()
  })
  it('Tests each view in the console in dark mode', () => {
    cy.get('[aria-label=toolbar-theme-toggle]').click()
    cy.get('[aria-label=console-drawer-icon-Map]').click()
    cy.wait(1000)
    cy.get('[id=map-component]').screenshot()
    cy.get('[aria-label=console-drawer-icon-Dashboard]').click()
    cy.wait(1000)
    cy.get('[id=dashboard]').screenshot()
    cy.get('[aria-label=console-drawer-icon-Table]').click()
    cy.wait(1000)
    cy.get('[id=table-component]').screenshot()
  })
  it('Reloads the API response', () => {
    cy.get('[aria-label=toolbar-reload-button]').click()
    cy.get('[aria-label=loading-text]').should('contain.text', 'Loading, please wait...')
  })
})